%% Example: split touching-cell binary mask images
% Edit inputDir and outputDir for your own data.

clear; clc;

repoRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(repoRoot, 'src'));

inputDir = fullfile(repoRoot, 'data', 'input_masks');   % TODO: change this
outputDir = fullfile(repoRoot, 'results');

summary = splitTouchingCellMasks(inputDir, outputDir, ...
    'FilePattern', '*.jpg', ...       % '*.png' or '*.tif' also works
    'MinArea', 5000, ...
    'Margin', 20, ...
    'SolidityThreshold', 0.90, ...
    'EccentricityThreshold', 0.70, ...
    'OpeningRadius', 2, ...
    'DistanceSigma', 1.2, ...
    'PeakHList', [1.2 0.9 0.6], ...
    'RidgeWidth', 4, ...
    'CutWidth', 4, ...
    'SmoothSigma', 10.0, ...
    'ShowFigure', true, ...
    'SaveResult', true, ...
    'DebugPrint', true);

disp(summary);
